const { fib, dist } = require('cpu-benchmark');
const {
  unlinkSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
} = require('node:fs');
const { join } = require('node:path');

function benchmark(op, timeLimit) {
  const start = performance.now();
  let ops = 0;
  let fails = 0;
  let successes = 0;
  let curTime = performance.now();
  while (curTime - start < timeLimit * 1000) {
    try {
      op();
      successes++;
    } catch (e) {
      fails++;
    } finally {
      ops++;
      curTime = performance.now();
    }
  }

  return { ops, successes, fails };
}

const name = process.argv[2];
function writeAndDeleteFile() {
  const dir = 'test' + name;
  const path = join(dir, 'test' + name);
  mkdirSync(dir);
  writeFileSync(path, contents);
  unlinkSync(dir);
}

const contents = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nec nibh ac risus eleifend scelerisque non a ligula. Mauris magna ipsum, fringilla nec sodales fringilla, mattis at nibh. Vivamus lacinia quam quis turpis pellentesque, vel lobortis sapien euismod. Nam nisl ligula, porta a vulputate nec, feugiat vitae nulla. Aliquam sagittis turpis sed ipsum tincidunt, nec tincidunt diam rutrum. Vivamus nec dapibus lacus. Curabitur eu lorem sed turpis imperdiet posuere. Aliquam nisi neque, convallis vitae vestibulum sed, scelerisque at orci. Sed fermentum odio vel magna pharetra, quis imperdiet mauris pretium. Phasellus facilisis posuere ante, id pellentesque risus elementum quis. Ut risus lorem, pellentesque a erat id, semper dignissim quam.

Aliquam pretium at ligula id dapibus. Donec arcu nibh, vehicula a dui a, lobortis feugiat sapien. Mauris ut purus ullamcorper, tempor nunc at, sagittis sem. Donec magna turpis, tincidunt eu porttitor eget, tincidunt eu nunc. Nam lacinia placerat mauris rutrum viverra. In leo orci, semper quis velit ac, tempor venenatis velit. Vivamus porta, lectus eu euismod elementum, mauris orci suscipit arcu, vel placerat nibh tellus at justo. Quisque id nunc non elit tristique lacinia ac eu magna. Ut tincidunt risus at dictum congue. Morbi mollis nunc a felis fringilla, in egestas metus iaculis. Nulla vel venenatis quam. Proin ut tristique felis. Donec faucibus velit et libero eleifend, ac fringilla urna bibendum.

Morbi ante odio, dapibus nec dapibus a, dignissim ac lorem. Nullam odio nibh, rhoncus non sapien et, egestas vulputate erat. Cras dolor dolor, semper vitae ultricies ac, maximus vel diam. Cras viverra, justo eu faucibus porttitor, risus ligula auctor nisi, eu varius magna mauris sit amet nunc. Duis a hendrerit libero. Quisque metus dui, blandit ac mattis vitae, ullamcorper vitae justo. Donec et pharetra elit. Maecenas malesuada dui ac tellus condimentum, a vulputate libero sodales. Nam commodo, orci ut scelerisque malesuada, est enim porttitor metus, vel posuere leo massa eu magna. Curabitur ultrices rutrum nisi, ac dignissim mauris auctor nec.

Praesent ultrices ex at enim commodo tempus. Quisque id semper sapien. Morbi varius vitae est eu porta. Pellentesque non nunc ligula. Nullam feugiat pharetra ex, vitae porta elit eleifend ut. Nam eget purus tortor. Nulla in libero odio. Pellentesque sed tempus mi. Proin in nulla convallis, auctor nulla eget, interdum sapien. Donec pharetra libero eget mauris luctus feugiat. Aenean nisi mauris, tincidunt nec enim eu, aliquam tristique diam.

Sed vel risus in tellus ultricies imperdiet. Maecenas luctus risus vel est tincidunt interdum. Cras gravida at neque a eleifend. Suspendisse potenti. Aenean quis massa quis nulla euismod lacinia id egestas nibh. Mauris rhoncus libero et tincidunt cursus. Sed ac eros dolor. Vestibulum sodales eros eu facilisis tincidunt. Vestibulum vehicula sed massa quis tincidunt. Nam viverra vel urna quis hendrerit. Mauris sed est pharetra, interdum mi sit amet, varius metus. Integer bibendum eu magna a lacinia. Fusce venenatis massa at rutrum molestie.

Ut egestas nisl et nisl tempor, sit amet dapibus ex scelerisque. Pellentesque vitae velit ut augue faucibus volutpat ac vel massa. Nunc bibendum diam porttitor turpis dignissim, ut tincidunt sapien pharetra. Curabitur vulputate nulla ipsum, consequat molestie magna pulvinar vel. Phasellus consequat magna tempus nisi tincidunt, non convallis nunc consequat. Proin venenatis neque ac pretium laoreet. Aliquam et commodo nisl, eu aliquam orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque ut dolor nec dolor molestie tincidunt. In vitae magna eget tortor accumsan commodo. Suspendisse ut massa mattis eros accumsan vestibulum eu ac eros. Suspendisse luctus augue sit amet ligula interdum, sed condimentum dui maximus.

Duis commodo risus et molestie finibus. In sagittis elementum enim, eu congue sapien sollicitudin id. Nunc a enim metus. Curabitur ut risus in turpis rutrum feugiat at quis nunc. Integer convallis vestibulum sem eu convallis. Cras cursus efficitur erat, quis porttitor nulla consequat ac. Aliquam finibus odio a sapien egestas, non molestie sem pellentesque.

Donec fringilla tortor sem, eu auctor dui hendrerit consectetur. Integer ex velit, faucibus quis tortor lobortis, imperdiet tempus quam. Cras finibus augue ac tortor volutpat, in tristique enim faucibus. Nunc pretium lorem nec lacus rhoncus, in sodales quam vehicula. Donec cursus sit amet mauris congue pulvinar. Ut quis sodales justo, at pulvinar felis. Vivamus sit amet urna volutpat, hendrerit lectus sed, pretium dui. Suspendisse commodo arcu vitae urna egestas, vitae cursus purus aliquet. Sed a quam non nibh tempor sagittis. Duis ut mollis massa. Etiam vehicula ultricies semper. In auctor est nibh, sed auctor velit eleifend at. Vivamus vitae cursus dolor. Vivamus aliquam, mi eget ultrices sagittis, arcu dolor lacinia nisl, eget accumsan massa lorem nec nulla. Morbi blandit vel massa non dignissim. Nam tincidunt semper arcu feugiat accumsan.

Etiam vulputate hendrerit arcu, eget facilisis massa laoreet vitae. Integer varius ipsum purus, nec laoreet quam egestas non. Ut tincidunt, diam ac venenatis elementum, diam lectus pretium risus, vitae pellentesque dolor mi non mi. Proin at nisl a ligula varius fermentum vel nec enim. Nullam id enim sem. Mauris nec augue quis nulla pretium tristique in convallis orci. Morbi id commodo purus.

Aliquam condimentum ullamcorper dui eu luctus. Suspendisse sit amet libero ipsum. Donec sit amet mauris ac nulla bibendum tempus id ac nisi. Proin a venenatis ipsum. Nunc vitae turpis ipsum. Cras id tellus felis. Aliquam non velit quis ligula condimentum consectetur at quis velit. Quisque massa nunc, iaculis sed dolor nec, dictum fringilla libero. Sed semper orci eu mi congue vestibulum. Sed a dolor et enim dignissim laoreet ac fringilla dolor. Morbi pretium neque ac eros vehicula, et ultrices tellus bibendum. Maecenas porttitor posuere nulla ut auctor. Donec pulvinar metus vitae lacus tincidunt sodales. Phasellus scelerisque turpis tortor, ac placerat ante varius sed.

In aliquet tellus in lacus lobortis pretium. Vestibulum ac magna imperdiet, fermentum purus vel, sollicitudin tellus. In hac habitasse platea dictumst. Vestibulum ut felis libero. Pellentesque libero urna, volutpat sed molestie non, efficitur eget justo. Fusce volutpat volutpat justo blandit sollicitudin. Proin lacinia vehicula magna, vel pellentesque elit. Aliquam luctus a sem eget bibendum. Vestibulum laoreet ligula accumsan tortor facilisis semper. Pellentesque egestas efficitur est nec iaculis. Etiam lobortis magna egestas, pulvinar metus ac, hendrerit libero. Quisque eu euismod libero. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla hendrerit orci vel consectetur rhoncus. Proin volutpat auctor nunc at mollis.

Suspendisse dictum cursus leo, at pharetra ipsum pellentesque quis. Nullam at consequat eros. Nulla eu nunc dignissim, dignissim odio ac, bibendum tortor. Maecenas varius porta massa, non vulputate odio congue vitae. Curabitur tempus, magna nec ullamcorper mattis, justo libero finibus nunc, sollicitudin convallis lacus mi sed metus. Sed tristique nulla nisi. Cras felis dui, cursus quis mattis at, porta aliquet leo. Etiam aliquam libero ac dui egestas, ac elementum purus feugiat. Morbi quis erat eu metus interdum finibus. Ut tristique purus sed quam hendrerit, quis suscipit tortor laoreet. Donec et laoreet orci. Curabitur eu rutrum enim. Maecenas risus dolor, congue bibendum vestibulum id, volutpat porta augue. Nullam volutpat ligula in sapien ultricies, vehicula scelerisque diam lobortis.

Sed cursus nisi id velit pretium, in interdum lectus vehicula. Curabitur pellentesque a ante id imperdiet. Aenean feugiat ac nisi vitae eleifend. Proin tincidunt in sapien at scelerisque. Sed lacinia elementum imperdiet. Duis blandit elit mi. Morbi mattis, dui sit amet pharetra malesuada, massa quam sollicitudin justo, ac aliquam metus felis vitae turpis. Proin ligula quam, rhoncus nec ultricies sed, luctus vitae magna. Donec eget turpis nec justo feugiat feugiat vitae sit amet libero. Quisque interdum orci sed augue gravida dignissim. Sed porta porta pharetra. Fusce hendrerit rutrum mauris, eu varius arcu luctus sed. Etiam nec viverra urna, ac semper mauris. Proin eu rhoncus lectus, nec efficitur felis. Phasellus ut auctor turpis. Fusce rhoncus mattis elit quis sollicitudin.

Morbi placerat eu quam vel dictum. Vestibulum dui orci, bibendum vitae egestas nec, consequat vel enim. Proin pharetra dignissim eleifend. In eleifend eget erat eget tristique. Nullam viverra scelerisque augue, eu scelerisque mauris pharetra et. Nunc placerat lobortis felis. Proin ligula sem, sagittis et consequat eget, dictum a lectus. Etiam tempus nisl sit amet sapien mattis auctor. Sed cursus eros lorem, vitae imperdiet nunc tempus et.

Vestibulum faucibus ante nec nisl bibendum imperdiet. Etiam vitae leo tellus. Pellentesque consectetur ullamcorper nibh eget semper. Suspendisse orci tellus, dictum eget nunc id, aliquam ullamcorper felis. Donec purus eros, porta id erat vel, elementum imperdiet ipsum. Pellentesque volutpat sit amet ipsum id blandit. Vestibulum vehicula tortor nec sagittis gravida.

Nam a odio vitae mauris scelerisque tristique. Donec vitae sem nec augue faucibus tempor. Suspendisse orci quam, pretium sit amet rhoncus non, rhoncus in risus. Proin leo urna, congue nec arcu at, laoreet luctus ex. Donec euismod at diam a tempor. Duis sagittis erat et enim eleifend, in maximus enim tincidunt. Morbi ac ultricies odio.

Duis lobortis lectus ac diam rutrum, sit amet aliquam lorem pulvinar. Donec congue dignissim interdum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus sit amet tristique turpis. Aliquam bibendum interdum massa vitae tincidunt. Quisque eu turpis odio. Vivamus sem lacus, bibendum id egestas in, consequat sed arcu. Nullam condimentum lorem at ante semper vulputate. Suspendisse ex ligula, suscipit ultricies convallis vitae, dictum non ipsum. Pellentesque posuere semper erat, at varius lacus congue id. Aenean aliquet iaculis nisl vel lacinia. Donec vehicula neque et ex sollicitudin dictum. Duis eget urna a nulla iaculis elementum.

Nam risus justo, pretium suscipit efficitur id, dictum nec ligula. Quisque fermentum suscipit tincidunt. Integer sed ex elementum, tristique odio porta, consectetur tellus. In id turpis ac leo fermentum rhoncus. Nunc scelerisque tortor magna, vel pellentesque massa aliquet finibus. Vivamus elementum magna a iaculis rhoncus. Nam sit amet eros sit amet eros scelerisque ullamcorper. Nulla in pharetra tortor, at laoreet sem. Donec eu pharetra ipsum, ut feugiat velit. Nullam fermentum porttitor libero a tincidunt. Curabitur at molestie sem. Maecenas mattis libero dolor, vel lacinia ex tincidunt et.

Aenean lacinia quam nec nulla pretium, et rhoncus velit auctor. Donec tempus, orci quis accumsan efficitur, tellus mi bibendum ante, in dapibus urna leo eget libero. Nulla sagittis vitae turpis et congue. Quisque nec feugiat nulla. Praesent eu lacus suscipit, iaculis elit quis, pretium elit. Quisque iaculis, est a dapibus feugiat, elit urna blandit nisi, ut pellentesque nunc elit sed risus. Integer pellentesque quam nec libero mollis dapibus.

Phasellus congue viverra magna, non rutrum libero rutrum ut. Aliquam blandit nibh id lacinia malesuada. In et risus vel tortor sollicitudin dapibus non vitae felis. Aliquam placerat, tellus quis bibendum pulvinar, eros felis fringilla lectus, non venenatis ipsum purus id quam. Nunc egestas orci vel tempor vulputate. Donec cursus ipsum ac laoreet posuere. Proin condimentum ligula vel nibh varius, ac sodales nisi suscipit. In sagittis non justo nec vulputate. Suspendisse interdum molestie velit non dapibus. Morbi vel varius nulla. Curabitur at mattis enim. In augue nibh, varius id lacus quis, ornare sollicitudin sapien.

Integer convallis urna et purus congue, sit amet luctus libero eleifend. Vivamus ornare porta velit sit amet interdum. Vivamus dignissim mollis mauris eu molestie. Vestibulum finibus, ipsum quis finibus malesuada, nisi tellus suscipit sem, ac faucibus magna nulla vitae dui. Mauris accumsan ante in felis finibus tincidunt. Nulla sapien purus, facilisis vitae ultricies eget, tristique vel dui. Mauris imperdiet efficitur eros ut consectetur. Maecenas nec neque ac ante vestibulum vulputate vitae vel lectus. Morbi lectus velit, bibendum in diam eget, mattis commodo dui. Aliquam erat volutpat. Nunc fringilla aliquam risus, quis aliquam ante iaculis ac. Proin mollis lorem non mattis posuere. Suspendisse ultricies nisl vel eros mollis, ut pretium urna blandit. Phasellus et est lorem. Donec eleifend mauris urna, in convallis massa lacinia eu. Nulla porta sagittis est, sit amet condimentum mauris.

Donec aliquam sem elit, a aliquet lectus mattis sit amet. Vivamus ac consectetur nisi. Mauris iaculis ullamcorper lobortis. Aliquam nec lobortis sem, id luctus mi. Vestibulum vitae est vitae mi semper auctor. Nullam in magna a ligula tempus pellentesque vel a ligula. Donec porttitor est vel enim euismod lobortis. Sed a blandit nisl. Donec faucibus quam mi, porttitor porta risus volutpat ut. Suspendisse libero diam, ornare sit amet semper eget, ultricies vitae neque.

Donec nunc sapien, vehicula facilisis mi et, tempus imperdiet mauris. Donec magna sapien, commodo non laoreet maximus, rutrum vitae augue. Vestibulum vitae leo sit amet orci tincidunt consequat in semper est. Duis congue, massa eu commodo egestas, odio mauris auctor eros, vitae vulputate justo ligula at ipsum. Nulla imperdiet massa velit, et accumsan mauris venenatis a. Vivamus scelerisque rutrum lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis ut consequat nisi. Nunc semper suscipit tristique. Suspendisse potenti. Vestibulum placerat justo auctor, gravida ipsum vitae, faucibus lorem. Praesent convallis non erat et sollicitudin. Maecenas turpis orci, cursus eu tristique nec, porta vitae libero. Cras laoreet magna eros, et feugiat est luctus ut. Aliquam posuere nec orci at vestibulum. Maecenas cursus laoreet libero, eget varius purus malesuada at.

Aliquam commodo felis metus, in molestie sem molestie id. Integer sit amet eleifend lacus. Maecenas faucibus ligula vel nunc rutrum lacinia. Aliquam venenatis dignissim mi ut viverra. Ut finibus eu arcu eget euismod. Donec sit amet pulvinar tellus. Vestibulum sagittis erat vel maximus eleifend. Nullam nec lobortis elit. Donec condimentum, quam in luctus maximus, diam nisl condimentum est, vel sagittis urna dui non justo. Fusce id iaculis tortor, vel tempor neque.

Curabitur sit amet lacus tellus. Ut at ipsum vel nisi placerat volutpat. Praesent feugiat lacus in libero placerat placerat. Nam posuere, erat molestie congue vehicula, leo leo malesuada enim, eget sodales magna sapien a sapien. Praesent velit odio, tincidunt ac lorem eget, tempor scelerisque ipsum. Cras enim ex, vehicula eu nibh id, iaculis placerat nibh. Curabitur gravida tortor in augue maximus, et elementum metus tempus. Morbi eleifend, quam nec elementum placerat, ipsum massa placerat massa, eget porttitor tellus purus a eros.

Mauris ut ultrices eros. Phasellus augue nisi, semper sed dictum et, lacinia vitae dui. Aenean elementum, risus sit amet bibendum mollis, est dolor mattis metus, in semper sapien quam nec leo. Fusce rhoncus nisl nisl, at consequat enim suscipit non. Nunc tempus ex non dolor feugiat ullamcorper. Phasellus fermentum enim ut libero malesuada, non varius leo finibus. Maecenas sed porta lectus. Etiam finibus lectus condimentum, lacinia nisl ac, suscipit purus. Integer id eleifend ante. Duis ornare vulputate mollis. Mauris iaculis leo sed arcu auctor gravida. Suspendisse erat enim, facilisis at venenatis vel, porttitor nec augue. Phasellus scelerisque, felis quis aliquam iaculis, mi mi mollis justo, id pulvinar tellus magna quis dolor. Nunc dapibus nisi sed finibus molestie. Nulla sit amet tellus id lorem vulputate vestibulum et eget dolor.

Pellentesque sagittis sem ac scelerisque ultricies. Nam in velit ex. Nullam lacinia, dui ac egestas fermentum, elit neque tempor dolor, sit amet bibendum tellus elit a nunc. Ut justo arcu, rhoncus quis lectus et, dapibus varius sapien. Sed purus ipsum, sodales et accumsan quis, pretium at risus. Ut ligula dui, pellentesque nec magna non, tempus gravida tortor. Suspendisse nisl turpis, dignissim quis est sit amet, dignissim viverra felis. Morbi tortor risus, dapibus lobortis aliquam et, volutpat eu justo. Donec laoreet magna faucibus ligula porttitor, vitae sodales purus fringilla. Donec pulvinar venenatis nisi, et dictum ex tempus id. Vestibulum quis ligula aliquet, pretium justo non, dictum orci. Cras faucibus dolor eu vehicula efficitur. Nam quis ante ut libero pulvinar ullamcorper eget ac nibh. Aenean sollicitudin accumsan velit, nec elementum dui sodales nec. Praesent consectetur dui ullamcorper efficitur suscipit. Mauris elementum libero felis, vitae euismod ligula mollis ac.

Integer dui dui, eleifend nec tempor eu, maximus quis eros. Aenean convallis iaculis ex, quis elementum nisi. Ut fermentum sed nisl ut varius. Mauris a est varius, egestas urna sed, feugiat lacus. Vestibulum ullamcorper nisl nec sem laoreet, ac dignissim augue tincidunt. Mauris bibendum mollis purus vel porttitor. Suspendisse condimentum ante eget ex tempus, vel aliquet nunc consectetur. Vivamus in leo at ante convallis varius in a eros. Duis sit amet consectetur neque. Donec tempus lacinia neque, quis porta metus varius id. Nullam sagittis sit amet urna id ultricies. Nullam ultrices dignissim libero. In eu quam lobortis, pharetra ex id, venenatis lacus. Aliquam erat volutpat. Donec pellentesque, lectus in volutpat porta, ex magna volutpat dolor, non condimentum ante metus bibendum dui. Nullam ullamcorper scelerisque eros, sit amet laoreet massa ornare id.

Aenean fringilla dui fringilla ipsum finibus interdum. Donec feugiat tincidunt commodo. Nullam ut turpis eget risus dapibus luctus. Integer bibendum urna eu lorem sollicitudin bibendum. Nam a elit sed diam pellentesque suscipit tempus id orci. Fusce dapibus tortor nec quam sollicitudin, a tempor felis tincidunt. Nulla eu elit efficitur, suscipit neque eget, tempor nisl. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum facilisis imperdiet nulla, ac sollicitudin diam eleifend ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Curabitur finibus nisl ac metus tincidunt sagittis. Morbi efficitur ante sed nulla euismod vehicula. Nam fringilla dolor id consequat congue. Cras consectetur ipsum vel consequat gravida. Integer ut euismod lorem. Donec mattis nunc id sem molestie malesuada. Vivamus vel dui ultrices, vehicula ipsum egestas, pulvinar sapien. Praesent elit elit, molestie quis diam sed, volutpat sagittis elit. Donec consectetur rutrum lacinia. Aenean ultrices suscipit sapien et tristique. Ut mi velit, congue in molestie sed, maximus eget nulla. In aliquet ligula quis lacus condimentum, vel consectetur mi vestibulum.

Donec et tincidunt dolor. Nam ornare aliquam dapibus. Vivamus vel gravida ipsum, a fringilla justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin malesuada nibh a tincidunt posuere. Praesent commodo id erat dictum elementum. Vivamus euismod sagittis ultrices. Sed semper mi ut maximus facilisis. Vestibulum facilisis sed nibh et facilisis. Pellentesque placerat massa id lectus facilisis, dignissim sodales sem eleifend. In vel nisl nisi. Nunc lacus erat, pulvinar eu elementum eu, tincidunt nec ex.

Nunc ut velit efficitur, molestie eros quis, pretium diam. Mauris luctus lacinia aliquet. Duis facilisis iaculis diam, sit amet ullamcorper purus rhoncus non. Ut non mauris dapibus, commodo dui vel, suscipit nulla. Quisque in aliquet erat. Donec scelerisque nisi nec nibh finibus aliquam. Sed scelerisque velit quam. Aenean in sapien mi. Donec in leo blandit, dictum elit at, venenatis eros. Vivamus aliquam fermentum efficitur. Aliquam pharetra dictum massa sit amet malesuada. Phasellus porta risus ante, et posuere ipsum rhoncus ut. Aliquam at felis sit amet mi consequat interdum. Nulla fermentum quam mi, sed egestas neque bibendum eget. Cras tempor dolor nec lectus pulvinar, eget finibus orci pharetra.

Aenean quis ex a lectus faucibus porta. Etiam vulputate euismod nisi eget vulputate. Phasellus neque tortor, porttitor eget iaculis non, congue ut turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas sit amet sem sed orci fringilla fermentum ut quis odio. Phasellus eget metus turpis. Vivamus sodales magna ipsum, quis rutrum metus molestie ut.

Aenean non porttitor tellus. Pellentesque laoreet dui sapien, ut porta ipsum vehicula in. In pretium dignissim rutrum. In et nunc vulputate, imperdiet felis vel, egestas quam. Suspendisse placerat accumsan velit sed hendrerit. Etiam fringilla pellentesque gravida. Nullam vitae lacus mauris. Quisque at blandit diam. Fusce dignissim, ligula at vestibulum aliquam, sapien diam maximus odio, non facilisis ligula magna ac ex. Vestibulum vehicula ornare luctus. Phasellus et sapien justo.

Quisque ipsum dolor, malesuada maximus ullamcorper at, scelerisque eu lacus. Cras feugiat ornare enim, at venenatis purus tristique ut. Quisque tempus vel eros quis suscipit. Mauris in suscipit nunc, condimentum mattis nibh. Ut ante tortor, consequat ut libero vitae, ullamcorper faucibus leo. Quisque tincidunt augue quis posuere eleifend. Phasellus tempor tempor dolor sit amet auctor. Cras euismod hendrerit urna, quis euismod tellus iaculis eget. Vivamus tristique, leo ac cursus fermentum, tortor enim ullamcorper libero, in pharetra odio enim sed mi. Quisque ante ex, facilisis quis nibh sed, semper tincidunt dolor. Sed gravida ex sed elit tempus, vel hendrerit leo tincidunt.

Duis id metus sit amet nulla laoreet dapibus. Maecenas sed leo eu dolor feugiat imperdiet sed ut neque. Praesent pretium justo vel neque tincidunt vehicula. Curabitur scelerisque, sem sit amet iaculis volutpat, tortor arcu consectetur urna, ac condimentum dolor nulla id ipsum. Vivamus massa nibh, sodales eu ullamcorper suscipit, pretium non urna. Fusce enim lacus, hendrerit pellentesque lorem vitae, volutpat ultricies orci. Suspendisse eleifend faucibus arcu, a porttitor ligula tempor tempor. Pellentesque in ullamcorper odio, non auctor augue. Etiam viverra scelerisque nunc eu congue. Sed laoreet elit a nunc volutpat, in eleifend lorem scelerisque. Nulla aliquet sapien quis magna viverra, feugiat molestie enim lobortis. Sed faucibus ex eget aliquet imperdiet. Morbi quam ex, interdum at finibus at, hendrerit non elit. Nulla gravida erat vel libero pulvinar porta. In tincidunt venenatis purus, maximus placerat diam elementum sit amet.

Maecenas hendrerit nibh nisl, a lobortis lacus sodales at. Maecenas tempor tortor eu diam suscipit faucibus. Curabitur faucibus vulputate magna, eu vehicula tortor feugiat eu. Proin in odio sodales, molestie augue eu, dictum eros. Nulla rutrum dui quis erat lobortis, id faucibus ipsum rhoncus. Pellentesque eleifend ipsum massa, id viverra orci aliquam ac. Vivamus interdum diam auctor est iaculis, sed venenatis felis hendrerit. Etiam ut dolor congue, sagittis libero ut, vehicula dui. Donec auctor ex fringilla malesuada egestas. Nam sed rutrum risus. Cras libero lectus, efficitur vitae lectus id, pretium interdum nunc. Suspendisse sed lectus lectus.

Proin ligula turpis, lobortis a pellentesque nec, mattis vitae neque. Sed vel lectus vel tellus scelerisque imperdiet vel a elit. Vestibulum risus neque, rhoncus ut ipsum et, dignissim congue enim. Vivamus mi dolor, volutpat eu posuere ut, sagittis id dui. Integer pellentesque volutpat mauris, at malesuada ex commodo tincidunt. Duis nisi lacus, sollicitudin eu venenatis a, interdum vel ex. Curabitur mattis dui libero, et tristique nibh tincidunt eu.

Etiam neque ante, tristique eget rhoncus id, dapibus ac tortor. Ut laoreet porttitor eros sed eleifend. Integer eget diam fermentum sapien tristique porta. Praesent aliquam feugiat scelerisque. Donec varius iaculis mauris, nec sodales urna consequat vel. Maecenas luctus nibh ut ipsum sagittis porta. Sed condimentum convallis nunc, at faucibus tortor. Suspendisse tempus sed libero ac varius. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut commodo felis ac ipsum bibendum blandit. Nam in ante ultrices est feugiat fringilla. Duis risus mauris, iaculis tempor fringilla fermentum, vulputate at justo. Integer nec venenatis justo. Vivamus vel fringilla nunc, eget sagittis urna.

Nulla hendrerit maximus metus quis condimentum. Integer auctor ex quis libero pharetra, quis facilisis neque vehicula. Praesent vestibulum, velit sed aliquet pharetra, massa neque feugiat mi, sit amet laoreet felis purus eu diam. Ut congue mauris ut mi viverra, a tincidunt lacus blandit. Sed laoreet velit justo, eget ornare justo laoreet mollis. Vestibulum id ex consectetur neque iaculis tincidunt. Sed consectetur tellus leo, at auctor tellus commodo in. Nulla a euismod nunc, ac lacinia orci.

Sed porta non leo id hendrerit. Morbi accumsan at sapien ac efficitur. Aenean at porta neque. Nullam porttitor arcu iaculis purus mattis commodo. Quisque lectus libero, pellentesque fringilla purus ac, auctor rutrum odio. Ut aliquet, urna non cursus placerat, eros nunc pellentesque massa, sit amet rhoncus magna odio et sem. Curabitur urna turpis, luctus vel tristique at, semper fringilla est. Praesent tempor condimentum nunc, ut ornare diam convallis vel. Integer ultricies malesuada dolor, vel molestie orci molestie porttitor. Suspendisse at velit arcu. Mauris varius, ante vel laoreet lobortis, felis nibh porta dolor, nec interdum est mi ac ligula.

Nullam ultrices magna a ligula cursus, ut consequat ligula porta. Sed iaculis vel urna malesuada malesuada. Aliquam sagittis risus quis blandit auctor. Pellentesque vel orci sed justo porta venenatis at at elit. Aenean fermentum a metus quis efficitur. Praesent consectetur lectus quis lacus finibus euismod. Mauris malesuada consequat nunc. In bibendum, tortor nec porttitor hendrerit, nulla ex placerat tortor, eu imperdiet urna nulla ut nulla.

Cras risus purus, vehicula nec scelerisque vel, elementum nec nisi. Curabitur ut mauris nec dolor mollis egestas nec eget urna. Fusce odio justo, pulvinar accumsan bibendum sed, vulputate sit amet nisl. Curabitur bibendum purus at eros cursus varius. Aliquam ac dolor tellus. Praesent gravida dapibus dui semper tincidunt. Aenean nec ligula vel quam condimentum malesuada. Quisque dignissim magna ut sodales congue. Nunc tincidunt mi at mi tempor, quis egestas nisl sagittis.

Vivamus ut augue vel eros fringilla vestibulum vitae et risus. Etiam neque diam, malesuada non augue nec, feugiat facilisis quam. Morbi vehicula, dolor non finibus faucibus, sapien metus tempus arcu, quis vulputate leo lectus quis lorem. Mauris a lacinia felis. Morbi dictum euismod eros quis porta. Duis id dolor libero. In congue lorem sit amet ante tincidunt rhoncus. Maecenas eget tristique lorem. Mauris id tristique ipsum. Aenean non mollis felis. Nunc luctus, odio at hendrerit feugiat, nibh libero ultricies felis, et mollis lorem ligula eget tortor. Sed pulvinar urna vel dignissim porta. Pellentesque placerat euismod libero, vel sollicitudin purus pellentesque tempor.

Sed pellentesque volutpat quam, at interdum dolor pulvinar quis. Nulla et ultricies arcu. Aenean tristique elementum nunc, sed dignissim metus ultricies ac. Aliquam nec ex vel massa ornare facilisis eget a mauris. Praesent sed luctus nisl. Quisque sodales mauris ac facilisis mattis. Nunc vulputate justo quis felis molestie, quis consequat velit pretium. In hac habitasse platea dictumst.

Fusce neque sapien, tristique sed elit eu, feugiat placerat dolor. Duis consectetur nunc vitae rutrum sodales. Maecenas turpis dui, mattis sit amet posuere vel, tincidunt a mauris. Nam in leo maximus, pretium enim in, tempus lacus. Nam pulvinar magna eu enim dapibus, id tempus ante pulvinar. Etiam porttitor tellus quis nulla pellentesque laoreet. Donec ut ligula nisl.

Mauris cursus tellus eget velit dapibus, sed vehicula enim fermentum. Integer feugiat imperdiet tempor. Maecenas scelerisque quis neque sed volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras volutpat, nulla eu consectetur aliquam, lacus elit volutpat leo, vitae congue urna dolor non arcu. Sed ut magna vel eros ullamcorper fermentum at a felis. Etiam faucibus libero ex, ut luctus felis pellentesque quis. Praesent erat tortor, commodo id pharetra et, sollicitudin a leo. Integer non condimentum sapien.

Etiam non lacinia magna, ut ornare dolor. Suspendisse elementum libero est, eu congue justo consectetur vel. Nulla varius massa metus. Vestibulum posuere nec orci id condimentum. Aenean lorem neque, sodales ac metus quis, commodo sagittis tellus. Proin condimentum, dui a tristique bibendum, turpis leo ornare turpis, id varius purus dolor sit amet libero. Morbi elementum elit in nisi ultrices faucibus. Vestibulum pellentesque orci magna, a porttitor mi laoreet eget. Cras ornare risus eu sodales ullamcorper. Aenean elementum eget enim in mattis. Aliquam luctus dolor nisi, et laoreet dolor pretium sed. Praesent rutrum felis nec felis vulputate pulvinar. Suspendisse sit amet porttitor dolor. Vestibulum pharetra massa eros, non dapibus nunc ultricies vitae. Praesent aliquet vulputate turpis, in euismod purus venenatis sed. Nulla accumsan ipsum et arcu tristique interdum.

Vivamus id nibh convallis, pretium purus eget, blandit mi. Aliquam erat volutpat. Donec lacinia est nec odio elementum fermentum. Fusce eget sapien et ante pulvinar interdum. Vestibulum risus felis, fermentum vitae mattis sollicitudin, gravida sed massa. Mauris id orci et ligula feugiat maximus quis eget ex. Suspendisse et finibus est. Maecenas vulputate scelerisque felis, in convallis risus dignissim tincidunt. Donec condimentum sollicitudin lacus. Pellentesque sed mauris quis mi aliquet faucibus.

Phasellus vehicula accumsan enim sed rhoncus. Pellentesque eros magna, lobortis vitae vehicula vel, sagittis quis leo. Curabitur et est lectus. Nulla semper, lectus at sodales auctor, dolor lectus blandit urna, sit amet lacinia tellus nulla at lacus. Nam sit amet ante eget diam vehicula ornare id non sem. Etiam augue ex, pulvinar sit amet lacus quis, pulvinar posuere orci. Donec lobortis orci metus, nec volutpat justo semper malesuada. Proin faucibus tincidunt velit, id placerat magna scelerisque ut. Etiam ac sapien quam. Nunc condimentum venenatis quam iaculis tempus. Suspendisse vitae efficitur erat, vitae egestas ex. Donec quis sem eu magna mollis vestibulum vel ut enim. Suspendisse in tempus lorem, in rutrum arcu. Quisque lectus velit, venenatis nec neque nec, iaculis elementum massa. Sed eu mauris a arcu scelerisque placerat eget maximus diam.`;

const data = [];
const passes = 100;
for (let i = 0; i < passes; i++) {
  const duration = fib(41); // Returns time required (ms)
  // to calculate the 41. fibonacci number recursively.
  const ops = dist(1000); // Returns the amount of operations
  // (distance matrix calculations) in 1000ms

  data.push({ duration, ops });
}

const avgDuration = data.reduce((acc, d) => acc + d.duration, 0) / data.length;
const avgOps = data.reduce((acc, d) => acc + d.ops, 0) / data.length;

console.log(avgDuration, `average duration over ${passes} passes`); // Average duration
console.log(avgOps, `average ops over ${passes} passes`); // Average ops
